CREATE TABLE [dbo].[TestTable]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FOO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TestTable] ADD CONSTRAINT [PK__TestTabl__3214EC27074382B7] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
