CREATE TABLE [dim].[dateNoTime]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Date] [date] NULL
) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [UQ_INDEX0] ON [dim].[dateNoTime] ([Date]) WITH (IGNORE_DUP_KEY=ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_Index0] ON [dim].[dateNoTime] ([ID]) INCLUDE ([Date]) ON [PRIMARY]

GO
ALTER TABLE [dim].[dateNoTime] ADD CONSTRAINT [PK__dateNoTi__3214EC2734CB9086] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
