CREATE TABLE [dim].[dateNoTime]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Date] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dim].[dateNoTime] ADD CONSTRAINT [PK__dateNoTi__3214EC2734CB9086] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
